import { useState, useCallback } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { rackApi, warehouseApi } from "@/api/warehouseApi";
import type { Rack, CreateRackDto } from "@/types/warehouse.types";
import { PageHeader } from "@/components/shared/PageHeader";
import { DataTableShell } from "@/components/shared/DataTableShell";
import { StatusBadge } from "@/components/shared/StatusBadge";
import { CrudFormDialog, FieldDef } from "@/components/shared/CrudFormDialog";
import { DeleteConfirmDialog } from "@/components/shared/DeleteConfirmDialog";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Pencil, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { useTranslation } from "react-i18next";

export default function RacksPage() {
  const { t } = useTranslation();
  const qc = useQueryClient();

  const fields: FieldDef[] = [
    { key: "warehouse_id", label: t('racks.warehouse'), type: "select", required: true, options: [] },
    { key: "aisle", label: t('racks.aisle'), type: "text", placeholder: t('racks.eg1') },
    { key: "row", label: t('racks.row'), type: "text", placeholder: t('racks.eg3') },
    { key: "column", label: t('racks.column'), type: "text", placeholder: t('racks.eg2') },
    { key: "level", label: t('racks.level'), type: "text", placeholder: t('racks.eg1') },
    { key: "name", label: t('racks.rackNameAuto'), type: "text", required: true, readOnly: true, placeholder: t('racks.autoGenerated') },
    { key: "capacity_boxes", label: t('racks.capacityBoxes'), type: "number", placeholder: t('racks.cap100') },
    { key: "qr_code", label: t('racks.qrCode'), type: "text", placeholder: t('racks.optional') },
    { key: "is_active", label: t('common.status'), type: "switch", defaultValue: true },
  ];
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editing, setEditing] = useState<Rack | null>(null);
  const [deleting, setDeleting] = useState<Rack | null>(null);
  const [page, setPage] = useState(1);
  const [searchInput, setSearchInput] = useState("");
  const [search, setSearch] = useState("");
  const [selectedWarehouseId, setSelectedWarehouseId] = useState<string>("all");
  const [formValues, setFormValues] = useState<Record<string, any>>({});

  const listParams = {
    page,
    limit: 25,
    search: search.trim() || undefined,
    warehouse_id: selectedWarehouseId !== "all" ? selectedWarehouseId : undefined,
    sortBy: "created_at" as const,
    sortOrder: "DESC" as const,
  };

  const { data: warehousesData } = useQuery({
    queryKey: ["warehouses", { limit: 500 }],
    queryFn: () => warehouseApi.getAll({ limit: 500 }),
  });

  const warehouseOptions =
    warehousesData?.data?.map((w) => ({
      value: w.id,
      label: `${w.code} - ${w.name}`,
    })) ?? [];

  const { data, isLoading } = useQuery({
    queryKey: ["racks", listParams],
    queryFn: () => rackApi.getAll(listParams),
  });

  const racks: Rack[] = data?.data ?? [];
  const meta = data?.meta ?? null;

  const handleSearchChange = useCallback((value: string) => {
    setSearchInput(value);
    setSearch(value);
    setPage(1);
  }, []);

  const handleFormValueChange = (key: string, value: any) => {
    setFormValues(prev => {
      const next = { ...prev, [key]: value };
      
      // Auto-generate name based on Warehouse Initials - A aisle R row C column L level
      const whId = next.warehouse_id;
      const wh = warehouseOptions.find(o => o.value === whId);
      // Extract the name part (after ' - ') and take the first 3 characters
      const whName = wh ? wh.label.split(' - ')[1] : '';
      const whInitial = whName ? whName.substring(0, 3).toUpperCase().replace(/\s/g, '') : '';
      
      const parts: string[] = [];
      if (whInitial) parts.push(whInitial);
      if (next.aisle) parts.push(`A${next.aisle}`);
      if (next.row) parts.push(`R${next.row}`);
      if (next.column) parts.push(`C${next.column}`);
      if (next.level) parts.push(`L${next.level}`);
      
      if (parts.length > 0) {
        next.name = parts.join('-');
      }

      return next;
    });
  };

  const saveMutation = useMutation({
    mutationFn: async (fd: Record<string, unknown>) => {
      const payload: any = {
        warehouse_id: String(fd.warehouse_id),
        name: String(fd.name),
        aisle: fd.aisle ? String(fd.aisle) : null,
        row: fd.row ? String(fd.row) : null,
        column: fd.column ? String(fd.column) : null,
        level: fd.level ? String(fd.level) : null,
        capacity_boxes:
          fd.capacity_boxes !== undefined && fd.capacity_boxes !== ""
            ? Number(fd.capacity_boxes)
            : null,
        qr_code: fd.qr_code ? String(fd.qr_code) : null,
        is_active: Boolean(fd.is_active),
      };

      if (editing) {
        return rackApi.update(editing.id, payload);
      }
      return rackApi.create(payload);
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["racks"] });
      setDialogOpen(false);
      setEditing(null);
      toast.success(editing ? t('racks.rackUpdated') : t('racks.rackCreated'));
    },
    onError: (e: any) => {
      toast.error(e?.response?.data?.error?.message ?? "Operation failed");
    },
  });

  const deleteMutation = useMutation({
    mutationFn: (id: string) => rackApi.delete(id),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["racks"] });
      setDeleting(null);
      toast.success(t('racks.rackDeleted'));
    },
  });

  const columns = [
    { key: "name", label: t('racks.rackName') },
    { key: "aisle", label: t('racks.aisle'), render: (r: any) => r.aisle ?? "—" },
    { key: "row", label: t('racks.row'), render: (r: any) => r.row ?? "—" },
    { key: "column", label: t('racks.col'), render: (r: any) => r.column ?? "—" },
    { key: "level", label: t('racks.level'), render: (r: any) => r.level ?? "—" },
    { key: "capacity_boxes", label: t('racks.capacity'), render: (r: any) => r.capacity_boxes ?? "—" },
    { key: "occupied_boxes", label: t('racks.occupied'), render: (r: any) => r.occupied_boxes ?? 0 },
    { key: "available_boxes", label: t('racks.available'), render: (r: any) => r.available_boxes ?? r.capacity_boxes ?? "—" },
    {
      key: "warehouse",
      label: t('racks.warehouse'),
      render: (r: Rack) => warehouseOptions.find((w) => w.value === r.warehouse_id)?.label ?? "—",
    },
    {
      key: "is_active",
      label: t('common.status'),
      render: (r: Rack) => <StatusBadge status={r.is_active ? "active" : "inactive"} />,
    },
    {
      key: "actions",
      label: t('common.actions'),
      render: (r: Rack) => (
        <div className="flex gap-1">
          <Button
            variant="ghost"
            size="icon"
            className="h-8 w-8"
            onClick={() => {
              setEditing(r);
              setFormValues(r);
              setDialogOpen(true);
            }}
          >
            <Pencil className="h-4 w-4" />
          </Button>
          <Button
            variant="ghost"
            size="icon"
            className="h-8 w-8 text-destructive"
            onClick={() => setDeleting(r)}
          >
            <Trash2 className="h-4 w-4" />
          </Button>
        </div>
      ),
    },
  ];

  const formFields: FieldDef[] = fields.map((f) =>
    f.key === "warehouse_id" ? { ...f, options: warehouseOptions } : f
  );

  return (
    <div>
      <PageHeader
        title={t('racks.title')}
        subtitle={t('racks.subtitle')}
        onAdd={() => {
          setEditing(null);
          setFormValues({ warehouse_id: selectedWarehouseId !== "all" ? selectedWarehouseId : "" });
          setDialogOpen(true);
        }}
        addLabel={t('racks.addRack')}
      >
        <div className="flex items-center gap-2">
          <Select value={selectedWarehouseId} onValueChange={(val) => { setSelectedWarehouseId(val); setPage(1); }}>
            <SelectTrigger className="w-[200px] h-9">
              <SelectValue placeholder={t('racks.allWarehouses')} />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">{t('common.viewAll')}</SelectItem>
              {warehouseOptions.map((opt) => (
                <SelectItem key={opt.value} value={opt.value}>
                  {opt.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </PageHeader>
      <DataTableShell<Rack>
        data={racks}
        columns={columns}
        searchKey="name"
        searchPlaceholder={t('racks.searchRack')}
        serverSide
        searchValue={searchInput}
        onSearchChange={handleSearchChange}
        paginationMeta={meta}
        onPageChange={setPage}
        isLoading={isLoading}
      />
      <CrudFormDialog
        open={dialogOpen}
        onClose={() => {
          setDialogOpen(false);
          setEditing(null);
          setFormValues({});
        }}
        onSubmit={(d) => saveMutation.mutateAsync(d)}
        fields={formFields}
        title={editing ? t('racks.editRack') : t('racks.newRack')}
        initialData={editing}
        loading={saveMutation.isPending}
        onValueChange={handleFormValueChange}
        values={formValues}
      />
      <DeleteConfirmDialog
        open={!!deleting}
        onClose={() => setDeleting(null)}
        onConfirm={() => deleting ? deleteMutation.mutateAsync(deleting.id) : Promise.resolve()}
        loading={deleteMutation.isPending}
      />
    </div>
  );
}